### ISSUE TITLE
Week 6 - Book 1 : Tokenizer 사용하기 & OpenAI Playground 사용하기

### ISSUE THREAD

**Issue by 0yeonnnn0** [GPbl-AI/Assignments#14]
# Week6 - Book1 : Tokenizer 사용하기 & OpenAI Playground 사용하기
<hr/>

### 1. Tokenizer 사용하기

1. 먼저 본인의 ChatGPT에 들어가 가장 마음에 들었던 문답을 정합니다.

2. Tokenizer를 활용하여 질문과 답변에 대한 토큰이 얼마나 들었는지 확인합니다.

3. OpenAI GPT API Pricing Calculator에서 본인의 문답 1회에 대한 가격을 확인합니다.

**제출 형식**

- GPT와 본인의 문답 캡쳐
- Tokenizer를 활용하여 문/답의 토큰 갯수 캡쳐
- OpenAI GPT API Pricing Calculator의 화면 캡쳐 (gpt4o 모델은 필수)

https://gptforwork.com/tools/openai-chatgpt-api-pricing-calculator

### 2. OpenAI Playground 사용하기

두 가지 중 하나의 상황에 몰입해 봅시다.
- 대학원생이 되어 대학 논문 작성
- 시인이 되어 시를 쓰기

두 가지 상황에서 본인의 Challenge가 있을 하나의 질문을 정하고, 
생성 옵션을 변경해가며 어떠한 효과적인 변화가 있는지 분석하기

**필수 요건**
- 최소 3가지의 생성 옵션 변경
- 본인의 상황에서 본인이 생각하는 최적의 생성 옵션에 대해 근거와 함께 적어봅시다.

<hr/>

## 과제 제출 형식
1. 이름
2. 과제 Repository 링크

<hr/>

## 마감일
- 11월 11일 (월) 23:59까지

**Comment by nukktae** [comment]
1. Anu
2. [ai_anu_dongyeon.pdf](https://github.com/user-attachments/files/17694896/ai_anu_dongyeon.pdf)

**Comment by onjellyday** [comment]
1. Kihoon
2. 
[Kihoon.pdf](https://github.com/user-attachments/files/17709807/Kihoon.pdf)

**Comment by devkaspee** [comment]
1. 임호준
2. [Week_6_AI과제_임호준.pdf](https://github.com/user-attachments/files/17709943/Week_6_AI._.pdf)

**Comment by uxr-drna** [comment]
1. 나덕룡
2. [Week_6_Book1_Nathan.pdf](https://github.com/user-attachments/files/17711327/Week_6_Book1_Nathan.pdf)

**Comment by cathy0305** [comment]
1. 주나현
2. 
[Week 6-1.pdf](https://github.com/user-attachments/files/17711563/Week.6-1.pdf)
[Week 6-2.pdf](https://github.com/user-attachments/files/17711644/Week.6-2.pdf)

**Comment by caseyyyyyyyyyyyyyyyyyyyyy** [comment]
1. 이정희
2. [Week 6_Prompt Design.pdf](https://github.com/user-attachments/files/17712740/Week.6_Prompt.Design.pdf)

**Comment by nampaca123** [comment]
1. 남경인
2. [남경인.pdf](https://github.com/user-attachments/files/17721365/LLM.pdf)

**Comment by haram8009** [comment]
1. 이하람
2. https://github.com/GPbl-AI/assignment-haram/tree/main/book1/week6
