### ISSUE TITLE
Week1 - Book 1 : 스타터 코드 받기

### ISSUE THREAD

**Issue by 0yeonnnn0** [GPbl-AI/Assignments#3]
# Week1 - Book 1 : 스타터 코드 받기

<hr/>

## 필수 과제

1. 컴퓨터 언어들 중 한 가지를 선택하고 
2. GPT에게 그 언어로 "Hello world!"를 출력하는 코드를 달라고 요청하고
3. GPT와의 대화 및 실행한 결과 캡쳐해서 올려두기

<hr/>

## 기타 요구사항

- 요구사항 1 : 파일은 Readme.md 또는 pdf로 만들어주세요.

<hr/>

## 과제 제출 형식
1. 이름
2. 과제 Repository 링크

<hr/>

## 마감일
- 10월 1일 (화) 12:00까지
- 깃허브 사용법에 대해 알지 못하는 사람들도 있을 것 같아 제출 기한을 연장하였습니다.

**Comment by haram8009** [comment]
1. 이하람
2. https://github.com/GPbl-AI/assignment-haram/tree/main/book1/week1

**Comment by cathy0305** [comment]
1. 주나현
2. https://github.com/GPbl-AI/assignment-Nahyun/blob/main/ai%201%E1%84%8C%E1%85%AE%E1%84%8E%E1%85%A1%E1%84%80%E1%85%AA%E1%84%8C%E1%85%A6%20a.pdf

**Comment by nukktae** [comment]
1. 아노
2. https://github.com/nukktae/ai-homework/tree/main/week1

**Comment by nukktae** [comment]
아노
https://github.com/nukktae/ai-homework/blob/main/week1/Readme.md

**Comment by caseyyyyyyyyyyyyyyyyyyyyy** [comment]
이정희
[week1_assignment.pdf](https://github.com/user-attachments/files/17199737/week1_assignment.pdf)

**Comment by nampaca123** [comment]
남경인
[https://github.com/nampaca123/llm_firstAssignment_kdy/tree/master](url)
[LLM 1주차 과제_남경인.pdf](https://github.com/user-attachments/files/17199865/LLM.1._.pdf)

**Comment by devkaspee** [comment]
1. 임호준
2. [임호준_과제_DYK.pdf](https://github.com/user-attachments/files/17201101/_._DYK.pdf)

**Comment by uxr-drna** [comment]
1. 나덕룡
2. [AI_week1_book1_1.pdf](https://github.com/user-attachments/files/17201878/AI_week1_book1_1.pdf)

**Comment by onjellyday** [comment]
1. 김기훈
2. 
[Kihoon.pdf](https://github.com/user-attachments/files/17213369/Kihoon.pdf)
https://github.com/GPbl-AI/assignment-Kihoon/tree/main
